name: test_application
description: A new Flutter project.

publish_to: 'none' # 不发布到 pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # 这里可以添加资源文件路径
  # assets:
  #   - assets/images/
